repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hmrc/security-git-hooks
    rev: release/1.11.0
    hooks:
      - id: secrets_filecontent
        name: Checking staged files for sensitive content
        exclude: ".tar$|.gz$|.jar$|.7z$|.rar$|.bz2$|.zip$|.gzip$|.war$|.ear$|.xlsx$|.xls$|
          |.docx$|.doc$|.pptx$|.pdf$|.jpg$|.png$|.jpeg$|.tif$|.tiff$|.gif$|.bmp$|.webp$|
          |.svg$|.ico$|.psd$|.exe$|.dll$|.dmg$|.de$|.rpm$"
      - id: secrets_filename
        name: Checking staged files for sensitive file types
        exclude: ".tar$|.gz$|.jar$|.7z$|.rar$|.bz2$|.zip$|.gzip$|.war$|.ear$|.xlsx$|.xls$|
          |.docx$|.doc$|.pptx$|.pdf$|.jpg$|.png$|.jpeg$|.tif$|.tiff$|.gif$|.bmp$|.webp$|
          |.svg$|.ico$|.psd$|.exe$|.dll$|.dmg$|.de$|.rpm$"
      - id: hooks_version_check
        name: Checking local hooks against the latest release
        verbose: true
  - repo: local
    hooks:
      - id: python-safety-dependencies-check
        name: Safety Check
        entry: sh
        args: ["-c","chcp 65001; set PYTHONIOENCODING=utf-8; safety scan --policy-file .safety-policy.yml;"]
        language: system
        encoding: UTF-8
        verbose: true
      - id: python-bandit-check
        name: Bandit Check
        entry: sh
        args: ["-c","bandit -r . -ll -s B605"]
        language: system
        encoding: UTF-8
        verbose: true
      - id: return-policy
        name: return policy file
        entry: sh
        args: ["-c","mv .safety-policy.yml.bak .safety-policy.yml"]
        language: system
fail_fast: false
